baseurl = "http://bolobob.com/blog/"
languageCode = "ja-jp"
title = "勉強ブログ"
canonifyurls = true
theme = "angels-ladder"

[params]
  description = "勉強したことを残すブログです"
  author = "bolobob"

[taxonomies]
  category = "categories"
  tag = "tags"
